server:
  port: 19110
spring:
  application:
    name: niushuai-study-eureka-client
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: client1.eureka.cc
  client:
    service-url:
      defaultZone: http://server1.eureka.cc:19100/eureka
