server:
  port: 19411
spring:
  application:
    name: spring-cloud-feign-user-service
eureka:
  client:
    service-url:
      defaultZone: http://server1.eureka.cc:19100/eureka
niushuai:
  server:
    id: 1
    randomDelay: 1000