server:
  port: 19600
spring:
  application:
    name: config-server-niushuai
  cloud:
    config:
      fail-fast: true
      label: master
      server:
        git:
          uri: https://github.com/niushuai233/spring-cloud-config-server-niushuai
          searchPath: config-repo
logging:
  level:
    root:
      org.springframework: trace
