server:
  port: 19600
spring:
  application:
    name: config-server-niushuai
  cloud:
    config:
      server:
        git:
          uri: https://github.com/niushuai233/spring-cloud-config-server-niushuai
          search-paths: config-repo